version: 2
jobs:
  build:
    working_directory: /home/circleci
    docker:
      - image: node:10.11.0
    steps:
      - checkout
      - run: npm install
      - run: npm run build

workflows:
  version: 2
  build:
    jobs:
      - build: